rules:
  AIRBNB_TYPES: true
  AIRBNB_VARS: true
  AIRBNB_SCOPE: true
  AIRBNB_OBJECTS: true
  AIRBNB_ARRAYS: true
  AIRBNB_DESTRUCT: true
  AIRBNB_STRINGS: true
  AIRBNB_FUNCS: true
  AIRBNB_CLASSES: true
  AIRBNB_MODULES: true
  AIRBNB_ITER: true
  AIRBNB_ACCESS: true
  AIRBNB_SINGLE_DECL: true
  AIRBNB_UNARY: true
  AIRBNB_COMPARE: true
  AIRBNB_CONTROL: true
  AIRBNB_DOCS: true
  AIRBNB_FORMAT: true
  AIRBNB_COMMAS: true
  AIRBNB_SEMICOLON: true
  AIRBNB_NAMES: true
  AIRBNB_BOOL: true
  AIRBNB_STD: true
  AIRBNB_PERF: true
  AIRBNB_UNUSED: true
  AIRBNB_HOIST: true
  CLEAN_CLARITY: true
  CLEAN_NAMES: true
  CLEAN_SMALL_FUNCS: true
  CLEAN_COMMENTS: true
  CLEAN_ERRORS: true
  SOLID_SRP_A: true
  SOLID_SRP_B: true
  SOLID_SRP_C: true
  SOLID_OCP_A: true
  SOLID_OCP_B: true
  SOLID_OCP_C: true
  SOLID_LSP_A: true
  SOLID_LSP_B: true
  SOLID_LSP_C: true
  SOLID_ISP_A: true
  SOLID_ISP_B: true
  SOLID_ISP_C: true
  SOLID_DIP_A: true
  SOLID_DIP_B: true
  SOLID_DIP_C: true
  SOLID_DIP_D: true
  SOLID_DIP_E: true
  DRY: true
  KISS: true
  YAGNI: true
  TDA: true
  TESTS: true